### PR TITLE
Add support to embeds on messages

### PR DESCRIPTION
**Pull request by SrGaabriel**
(This was not tested)

### CODE REVIEW

**Comment by SrGaabriel** [comment]
This is not able for merge yet since the only HTTP sender that is supporting embeds right now is the Web Server one, because on the others I need to adapt the `Embed` object to a `EmbedResponse`.

**Comment by SrGaabriel** [comment]
Since only Kord's "core" module supports that conversion, I'm analyzing how they do this conversion to apply myself.

**Comment by SrGaabriel** [comment]
Now we can use embeds this way:

```kotlin
embed {
   author {
      name = "Admin"
      url = ""
      icon = user.avatar.displayAvatar
    }
    body {
      title = "My Embed!"
      description = "This is just a test embed!"
      color = Color.BLACK
    }
    field {
      name = "Is This Cool?"
      value = "Yes!"
      // inline = true
    field {
      name = "Is This Working?"
      value = "Probably"
      // inline = true
    footer {
      text = "This is the end of the embed!"
      icon = user.avatar.displayAvatar

**Comment by SrGaabriel** [comment]
I'm still planing on adding exceptions if a required field is missing instead of just invalidating the entire object.

**Comment by MrPowerGamerBR** [comment]
I still need to check this PR

**Pull request closed without merging**
